"""Add exercises to training plans

Revision ID: 5eadc6bb2faa
Revises: b083f1e0a1fc
Create Date: 2023-12-26 23:31:31.008633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eadc6bb2faa'
down_revision = 'b083f1e0a1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_training_history_training_plan', 'training_plan', ['training_plan_id'], ['id'])
        batch_op.drop_column('time_of_training')
        batch_op.drop_column('result')
        batch_op.drop_column('user_training_date')

    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.drop_column('exercises')

    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_training_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('time_of_training', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('progress_notes')
        batch_op.drop_column('training_plan_id')

    # ### end Alembic commands ###
