"""Add role column to user model

Revision ID: b2b60e874e44
Revises: 2c2fd6e6ce58
Create Date: 2023-12-29 01:33:44.495818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b60e874e44'
down_revision = '2c2fd6e6ce58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_progress', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('start_work',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('start_work',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('exercise_progress', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
